In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import numpy as np

## Read in the data

In [2]:
# read in the data
hmda_2020 = pd.read_csv('../data/msamd_12060_2020.csv') 
hmda_2021 = pd.read_csv('../data/msamd_12060_2021.csv')
hmda_2022 = pd.read_csv('../data/msamd_12060_2022.csv') 
hmda_2023 = pd.read_csv('../data/msamd_12060_2023.csv')
hmda_2024 = pd.read_csv('../data/msamd_12054_2024.csv')

C:\Users\Cat\AppData\Local\Temp\ipykernel_15376\211953371.py:2: DtypeWarning: Columns (22,23,24,26,27,28,29,30,31,32,33,38,43,44) have mixed types. Specify dtype option on import or set low_memory=False.
  hmda_2020 = pd.read_csv('../data/msamd_12060_2020.csv')
C:\Users\Cat\AppData\Local\Temp\ipykernel_15376\211953371.py:3: DtypeWarning: Columns (22,23,24,26,27,28,29,30,31,32,33,38,43,44) have mixed types. Specify dtype option on import or set low_memory=False.
  hmda_2021 = pd.read_csv('../data/msamd_12060_2021.csv')
C:\Users\Cat\AppData\Local\Temp\ipykernel_15376\211953371.py:4: DtypeWarning: Columns (22,23,24,26,27,28,29,30,31,32,33,38,43,44) have mixed types. Specify dtype option on import or set low_memory=False.
  hmda_2022 = pd.read_csv('../data/msamd_12060_2022.csv')
C:\Users\Cat\AppData\Local\Temp\ipykernel_15376\211953371.py:5: DtypeWarning: Columns (22,23,24,26,27,28,29,30,31,32,33,38,43,44) have mixed types. Specify dtype option on import or set low_memory=False.
  hmda_202

#### concatenate hmda for 2020-2024 together

In [3]:
hmda_2020['year'] = 2020
hmda_2021['year'] = 2021
hmda_2022['year'] = 2022
hmda_2023['year'] = 2023
hmda_2024['year'] = 2024

hmda_all = pd.concat([hmda_2020, hmda_2021, hmda_2022, hmda_2023, hmda_2024], ignore_index=True)

#### create a unique ID column for all rows of the data

In [5]:
hmda_all['unique_id'] = range(len(hmda_all))

#### count number of rows of full dataset before filtering --> 2,046,788

In [6]:
hmda_all[hmda_all.columns[0]].count() 

np.int64(2046788)

##### Remove all values that do not reflect approved and accepted/originated = 1, or denied = 3

In [7]:
# remove all values that do not reflect approved, denied, or approved but not accepted
# Description: The action taken on the covered loan or application
# Values:
# 1 - Loan originated
# 2 - Application approved but not accepted
# 3 - Application denied
# 4 - Application withdrawn by applicant
# 5 - File closed for incompleteness
# 6 - Purchased loan
# 7 - Preapproval request denied
# 8 - Preapproval request approved but not accepted

list_of_values_to_keep = [1,3]

hmda_all = hmda_all[hmda_all['action_taken'].isin(list_of_values_to_keep)]
hmda_all['action_taken'].unique()

array([1, 3])

##### change name of column

In [8]:
hmda_all['approved_originated_or_denied'] = hmda_all['action_taken']

##### Convert 1s and 3s to 1s and 0s

In [9]:
hmda_all['approved_originated_or_denied'] = hmda_all['approved_originated_or_denied'].replace({1 : 1, 3 : 0})

#### count number of rows that were approved originated or denied --> 1,340,915

In [10]:
# number of non-NaN values in first column
hmda_all[hmda_all.columns[0]].count()

np.int64(1340915)

##### Remove not applicable (could include applicants with little to no credit and exempt institutions) to eliminate legal entities like corporations etc from being included in the data instead of individuals

In [11]:
# remove not applicable (could include applicants with little to no credit) and exempt institutions
# to eliminate legal entitities like corporations etc from being included in the data instead of individuals

# Description: The name and version of the credit scoring model used to generate the credit score, or scores, relied on in making the credit decision
# Values:
# 1 - Equifax Beacon 5.0
# 2 - Experian Fair Isaac
# 3 - FICO Risk Score Classic 04
# 4 - FICO Risk Score Classic 98
# 5 - VantageScore 2.0
# 6 - VantageScore 3.0
# 7 - More than one credit scoring model
# 8 - Other credit scoring model
# 9 - Not applicable
# 1111 - Exempt

list_of_values_to_keep = [1,2,3,4,5,6,7,8]

hmda_all = hmda_all[hmda_all['applicant_credit_score_type'].isin(list_of_values_to_keep)]
hmda_all['applicant_credit_score_type'].unique()

array([2, 3, 1, 7, 4, 8, 6, 5])

#### count number of rows that were left after NA and Exempt were removed --> 1,169,761

In [12]:
# number of non-NaN values in first column
hmda_all[hmda_all.columns[0]].count()

np.int64(1169761)

##### Remove not applicable (could include applicants with little to no credit and exempt institutions) to eliminate legal entities like corporations etc from being included in the data instead of individuals`

In [13]:
# remove not applicable (could include applicants with little to no credit and exempt institutions)
# to eliminate legal entitities like corporations etc from being included in the data instead of individuals

# Description: The name and version of the credit scoring model used to generate the credit score, or scores, relied on in making the credit decision
# Values:
# 1 - Equifax Beacon 5.0
# 2 - Experian Fair Isaac
# 3 - FICO Risk Score Classic 04
# 4 - FICO Risk Score Classic 98
# 5 - VantageScore 2.0
# 6 - VantageScore 3.0
# 7 - More than one credit scoring model
# 8 - Other credit scoring model
# 9 - Not applicable
# 10 - No co-applicant
# 11 – FICO Score 9
# 12 – FICO Score 8
# 13 – FICO Score 10
# 14 – FICO Score 10T
# 15 - VantageScore 4.0
# 1111 - Exempt

list_of_values_to_keep = [1,2,3,4,5,6,7,8,10,11,12,13,14,15]

hmda_all = hmda_all[hmda_all['co-applicant_credit_score_type'].isin(list_of_values_to_keep)]
hmda_all['co-applicant_credit_score_type'].unique()

array([10,  1,  2,  3,  7,  4,  8,  5,  6, 11, 14])

#### count number of rows that were left after NA and Exempt were removed from co-applicant --> 942,372

In [14]:
# number of non-NaN values in first column
hmda_all[hmda_all.columns[0]].count()

np.int64(942372)

## Convert financial information to numeric

##### Coerce to numeric the loan_to_value_ratio 

In [15]:
print(hmda_all['loan_to_value_ratio'].dtype)
hmda_all['loan_to_value_ratio'] = pd.to_numeric(hmda_all['loan_to_value_ratio'], errors='coerce')
print(hmda_all['loan_to_value_ratio'].dtype)

object
float64


##### Coerce to numeric the property_value 

In [16]:
print(hmda_all['property_value'].dtype)
hmda_all['property_value'] = pd.to_numeric(hmda_all['property_value'], errors='coerce')
print(hmda_all['property_value'].dtype)

object
float64


##### Check data type of income

In [17]:
print(hmda_all['income'].dtype)

float64


##### Coerce to numeric the interest_rate 

In [18]:
print(hmda_all['interest_rate'].dtype)
hmda_all['interest_rate'] = pd.to_numeric(hmda_all['interest_rate'], errors='coerce')
print(hmda_all['interest_rate'].dtype)

object
float64


##### Coerce to numeric the rate_spread 

In [19]:
print(hmda_all['rate_spread'].dtype)
hmda_all['rate_spread'] = pd.to_numeric(hmda_all['rate_spread'], errors='coerce')
print(hmda_all['rate_spread'].dtype)

object
float64


## Scale appropriate financial information

#### Scale ffiec_msa_md_median_family_income

In [20]:
hmda_all['ffiec_msa_md_median_family_income_scaled'] = hmda_all['ffiec_msa_md_median_family_income'] / 1000

#### Scale loan_amount

In [21]:
hmda_all['loan_amount_scaled'] = hmda_all['loan_amount'] / 1000

#### Scale property_value

In [22]:
hmda_all['property_value_scaled'] = hmda_all['property_value'] / 1000

## Converting categorical data into numeric for the purpose of running a logistic regression

### AUS Automated Underwriting System

#### Melt the AUS columns into a smaller df to OHE those columns

In [23]:
# melting data into smaller df to ohe it
hmda_all_melted = hmda_all.melt(
    id_vars="unique_id", 
    value_vars=["aus-1", "aus-2", "aus-3", "aus-4", "aus-5"],
    var_name="aus_types", 
    value_name="aus_values"
) 

##### Fill in NaNs with 0s and convert to an integer from float

In [24]:
# fill NaNs with zeroes and change the data type to integer instead of float
hmda_all_melted["aus_values"] = hmda_all_melted["aus_values"].fillna(0).astype(int)

#### One Hot Encode data

In [25]:
# use OneHotEncoder
transformed = OneHotEncoder(sparse_output=False).set_output(transform="pandas")

# fit and transform the specific column
encoded_df = transformed.fit_transform(hmda_all_melted[["aus_values"]])

# combine the encoded columns back with the original df
hmda_all_melted = pd.concat([hmda_all_melted.drop(columns=["aus_values"]), encoded_df], axis=1)

##### Drop unnecessary columns 

In [26]:
hmda_all_melted = hmda_all_melted.drop(columns=["aus_values_0", "aus_types"])

##### Group by the unique_id column, add those values together, and reset the index

In [27]:
# group by the unique_id column, sum those values together, and reset the index
hmda_all_melted = hmda_all_melted.groupby("unique_id").sum().reset_index()

##### make aus_columns integers instead of floats

In [28]:
# make aus_columns integers instead of floats
aus_columns = ['aus_values_1', 'aus_values_2', 'aus_values_3', 
               'aus_values_4', 'aus_values_5', 'aus_values_6']

hmda_all_melted[aus_columns] = hmda_all_melted[aus_columns].fillna(0).astype(int)

#### Merge the AUS df and the original HMDA df together

In [29]:
hmda_all = hmda_all.merge(hmda_all_melted, on="unique_id")

### AE applicant_ethnicity

#### Melt the applicant_ethnicity columns into a smaller df to OHE those columns

In [30]:
# melting data into smaller df to ohe it
hmda_all_melted = hmda_all.melt(
    id_vars="unique_id", 
    value_vars=["applicant_ethnicity-1", "applicant_ethnicity-2", "applicant_ethnicity-3", 
                "applicant_ethnicity-4", "applicant_ethnicity-5"],
    var_name="ae_types", 
    value_name="ae_values"
) 

##### Fill in NaNs with 0s and convert to an integer from float

In [31]:
# fill NaNs with zeroes and change the data type to integer instead of float
hmda_all_melted["ae_values"] = hmda_all_melted["ae_values"].fillna(0).astype(int)

#### One Hot Encode data

In [32]:
# use OneHotEncoder
transformed = OneHotEncoder(sparse_output=False).set_output(transform="pandas")

# fit and transform the specific column
encoded_df = transformed.fit_transform(hmda_all_melted[["ae_values"]])

# combine the encoded columns back with the original df
hmda_all_melted = pd.concat([hmda_all_melted.drop(columns=["ae_values"]), encoded_df], axis=1)

##### Drop unnecessary columns 

In [33]:
hmda_all_melted = hmda_all_melted.drop(columns=["ae_values_0", "ae_types"])

##### Group by the unique_id column, add those values together, and reset the index

In [34]:
# group by the unique_id column, sum those values together, and reset the index
hmda_all_melted = hmda_all_melted.groupby("unique_id").sum().reset_index()

##### make ae_columns integers instead of floats

In [35]:
# make ae_columns integers instead of floats
ae_columns = ['ae_values_1', 'ae_values_2', 'ae_values_3', 
              'ae_values_4', 'ae_values_11', 'ae_values_12', 
              'ae_values_13', 'ae_values_14']

hmda_all_melted[ae_columns] = hmda_all_melted[ae_columns].fillna(0).astype(int)

#### Merge the AE df and the original HMDA df together

In [36]:
hmda_all = hmda_all.merge(hmda_all_melted, on="unique_id")

### CAE co-applicant_ethnicity

#### Melt the co-applicant_ethnicity columns into a smaller df to OHE those columns

In [37]:
# melting data into smaller df to ohe it
hmda_all_melted = hmda_all.melt(
    id_vars="unique_id", 
    value_vars=["co-applicant_ethnicity-1", "co-applicant_ethnicity-2", "co-applicant_ethnicity-3", 
                "co-applicant_ethnicity-4", "co-applicant_ethnicity-5"],
    var_name="cae_types", 
    value_name="cae_values"
) 

##### Fill in NaNs with 0s and convert to an integer from float

In [38]:
# fill NaNs with zeroes and change the data type to integer instead of float
hmda_all_melted["cae_values"] = hmda_all_melted["cae_values"].fillna(0).astype(int)

#### One Hot Encode data

In [39]:
# use OneHotEncoder
transformed = OneHotEncoder(sparse_output=False).set_output(transform="pandas")

# fit and transform the specific column
encoded_df = transformed.fit_transform(hmda_all_melted[["cae_values"]])

# combine the encoded columns back with the original df
hmda_all_melted = pd.concat([hmda_all_melted.drop(columns=["cae_values"]), encoded_df], axis=1)

##### Drop unnecessary columns 

In [40]:
hmda_all_melted = hmda_all_melted.drop(columns=["cae_values_0", "cae_types"])

##### Group by the unique_id column, add those values together, and reset the index

In [41]:
# group by the unique_id column, sum those values together, and reset the index
hmda_all_melted = hmda_all_melted.groupby("unique_id").sum().reset_index()

##### make cae_columns integers instead of floats

In [42]:
# make cae_columns integers instead of floats
cae_columns = ['cae_values_1', 'cae_values_2', 'cae_values_3', 
              'cae_values_4', 'cae_values_5', 'cae_values_11', 
              'cae_values_12', 'cae_values_13', 'cae_values_14']

hmda_all_melted[cae_columns] = hmda_all_melted[cae_columns].fillna(0).astype(int)

#### Merge the CAE df and the original HMDA df together

In [43]:
hmda_all = hmda_all.merge(hmda_all_melted, on="unique_id")

### AR applicant_race

#### Melt the applicant_race columns into a smaller df to OHE those columns

In [44]:
# melting data into smaller df to ohe it
hmda_all_melted = hmda_all.melt(
    id_vars="unique_id", 
    value_vars=["applicant_race-1", "applicant_race-2", "applicant_race-3", "applicant_race-4", "applicant_race-5"],
    var_name="ar_types", 
    value_name="ar_values"
) 

##### Fill in NaNs with 0s and convert to an integer from float

In [45]:
# fill NaNs with zeroes and change the data type to integer instead of float
hmda_all_melted["ar_values"] = hmda_all_melted["ar_values"].fillna(0).astype(int)

#### One Hot Encode data

In [46]:
# use OneHotEncoder
transformed = OneHotEncoder(sparse_output=False).set_output(transform="pandas")

# fit and transform the specific column
encoded_df = transformed.fit_transform(hmda_all_melted[["ar_values"]])

# combine the encoded columns back with the original df
hmda_all_melted = pd.concat([hmda_all_melted.drop(columns=["ar_values"]), encoded_df], axis=1)

##### Drop unnecessary columns 

In [47]:
hmda_all_melted = hmda_all_melted.drop(columns=["ar_values_0", "ar_types"])

##### Group by the unique_id column, add those values together, and reset the index

In [48]:
# group by the unique_id column, sum those values together, and reset the index
hmda_all_melted = hmda_all_melted.groupby("unique_id").sum().reset_index()

##### make ar_columns integers instead of floats

In [49]:
# make ar_columns integers instead of floats
ar_columns = ['ar_values_1', 'ar_values_2', 'ar_values_3', 
               'ar_values_4', 'ar_values_5', 'ar_values_6',
               'ar_values_7', 'ar_values_21', 'ar_values_22', 
               'ar_values_23', 'ar_values_24', 'ar_values_25', 
               'ar_values_26', 'ar_values_27', 'ar_values_41', 
               'ar_values_42', 'ar_values_43', 'ar_values_44']

hmda_all_melted[ar_columns] = hmda_all_melted[ar_columns].fillna(0).astype(int)

#### Merge the AR df and the original HMDA df together

In [50]:
hmda_all = hmda_all.merge(hmda_all_melted, on="unique_id")

### CAR co-applicant_race

#### Melt the co-applicant_race columns into a smaller df to OHE those columns

In [51]:
# melting data into smaller df to ohe it
hmda_all_melted = hmda_all.melt(
    id_vars="unique_id", 
    value_vars=["co-applicant_race-1", "co-applicant_race-2", "co-applicant_race-3", "co-applicant_race-4", "co-applicant_race-5"],
    var_name="car_types", 
    value_name="car_values"
) 

##### Fill in NaNs with 0s and convert to an integer from float

In [52]:
# fill NaNs with zeroes and change the data type to integer instead of float
hmda_all_melted["car_values"] = hmda_all_melted["car_values"].fillna(0).astype(int)

#### One Hot Encode data

In [53]:
# use OneHotEncoder
transformed = OneHotEncoder(sparse_output=False).set_output(transform="pandas")

# fit and transform the specific column
encoded_df = transformed.fit_transform(hmda_all_melted[["car_values"]])

# combine the encoded columns back with the original df
hmda_all_melted = pd.concat([hmda_all_melted.drop(columns=["car_values"]), encoded_df], axis=1)

##### Drop unnecessary columns 

In [54]:
hmda_all_melted = hmda_all_melted.drop(columns=["car_values_0", "car_types"])

##### Group by the unique_id column, add those values together, and reset the index

In [55]:
# group by the unique_id column, sum those values together, and reset the index
hmda_all_melted = hmda_all_melted.groupby("unique_id").sum().reset_index()

##### make car_columns integers instead of floats

In [56]:
# make car_columns integers instead of floats
car_columns = ['car_values_1', 'car_values_2', 'car_values_3',
               'car_values_4', 'car_values_5', 'car_values_6', 
               'car_values_7', 'car_values_8', 'car_values_21', 
               'car_values_22', 'car_values_23', 'car_values_24', 
               'car_values_25', 'car_values_26', 'car_values_27',
               'car_values_41', 'car_values_42', 'car_values_43', 
               'car_values_44']

hmda_all_melted[car_columns] = hmda_all_melted[car_columns].fillna(0).astype(int)

#### Merge the CAR df and the original HMDA df together

In [57]:
hmda_all = hmda_all.merge(hmda_all_melted, on="unique_id")

### DR denial_reason

#### Melt the denial_reason columns into a smaller df to OHE those columns

In [58]:
# melting data into smaller df to ohe it
hmda_all_melted = hmda_all.melt(
    id_vars="unique_id", 
    value_vars=["denial_reason-1", "denial_reason-2", "denial_reason-3", "denial_reason-4"],
    var_name="dr_types", 
    value_name="dr_values"
) 

##### Fill in NaNs with 0s and convert to an integer from float

In [59]:
# fill NaNs with zeroes and change the data type to integer instead of float
hmda_all_melted["dr_values"] = hmda_all_melted["dr_values"].fillna(0).astype(int)

#### One Hot Encode data

In [60]:
# use OneHotEncoder
transformed = OneHotEncoder(sparse_output=False).set_output(transform="pandas")

# fit and transform the specific column
encoded_df = transformed.fit_transform(hmda_all_melted[["dr_values"]])

# combine the encoded columns back with the original df
hmda_all_melted = pd.concat([hmda_all_melted.drop(columns=["dr_values"]), encoded_df], axis=1)

##### Drop unnecessary columns 

In [61]:
hmda_all_melted = hmda_all_melted.drop(columns=["dr_values_0", "dr_types"])

##### Group by the unique_id column, add those values together, and reset the index

In [62]:
# group by the unique_id column, sum those values together, and reset the index
hmda_all_melted = hmda_all_melted.groupby("unique_id").sum().reset_index()

In [63]:
hmda_all_melted.columns.unique()

Index(['unique_id', 'dr_values_1', 'dr_values_2', 'dr_values_3', 'dr_values_4',
       'dr_values_5', 'dr_values_6', 'dr_values_7', 'dr_values_8',
       'dr_values_9', 'dr_values_10', 'dr_values_1111'],
      dtype='object')

##### make dr_columns integers instead of floats

In [64]:
# make car_columns integers instead of floats
dr_columns = ['dr_values_1', 'dr_values_2', 'dr_values_3', 
               'dr_values_4', 'dr_values_5', 'dr_values_6', 
               'dr_values_7', 'dr_values_8', 'dr_values_9', 
               'dr_values_10', 'dr_values_1111']

hmda_all_melted[dr_columns] = hmda_all_melted[dr_columns].fillna(0).astype(int)

#### Merge the DR df and the original HMDA df together

In [65]:
hmda_all = hmda_all.merge(hmda_all_melted, on="unique_id")

### Filter AA Applicant Age

In [66]:
# ageapplicant
# Description: The age of the applicant
# Values:
# <25
# 25-34
# 35-44
# 45-54
# 55-64
# 65-74
# >74
# 8888

#### Exclude 8888, not an age category

In [67]:
list_of_values_to_keep = ['<25', '25-34', '35-44', '45-54', '55-64', '65-74', '>74']

hmda_all = hmda_all[hmda_all['applicant_age'].isin(list_of_values_to_keep)]
hmda_all['applicant_age'].unique()

array(['65-74', '35-44', '45-54', '25-34', '55-64', '>74', '<25'],
      dtype=object)

#### Create Hispanic vs. Not Hispanic 

In [68]:
# applicant_ethnicity-1
# Description: Ethnicity of the applicant or borrower
# Values:
# 1 - Hispanic or Latino
# 11 - Mexican
# 12 - Puerto Rican
# 13 - Cuban
# 14 - Other Hispanic or Latino
# 2 - Not Hispanic or Latino
# 3 - Information not provided by applicant in mail, internet, or telephone application
# 4 - Not applicable

#### Exclude info not provided and not applicable

In [69]:
hmda_all = hmda_all[~hmda_all['applicant_ethnicity-1'].isin([3, 4])]

In [70]:
# ethnicity columns
ethnicity_cols = ['applicant_ethnicity-1', 'applicant_ethnicity-2', 'applicant_ethnicity-3',
                  'applicant_ethnicity-4', 'applicant_ethnicity-5']
hispanic_nums = [1, 11, 12, 13, 14]

# indicator columns for each hispanic subcategory --> one per num
for num in hispanic_nums:
    hmda_all[f'ae_values_{num}'] = (hmda_all[ethnicity_cols] == num).any(axis=1)

# overall hispanic indicator -- 1 = Hispanic, 0 = Not Hispanic
hmda_all['is_hispanic'] = hmda_all[[f'ae_values_{num}' for num in hispanic_nums]].any(axis=1).astype(int)

# not hispanic indicator -- 1 = Not Hispanic, 0 = Hispanic
hmda_all['not_hispanic'] = (~hmda_all['is_hispanic'].astype(bool)).astype(int)

# hispanic vs. not hispanic label column
hmda_all['ethnicity_group'] = np.where(hmda_all['is_hispanic'], 'Hispanic', 'Not Hispanic')

In [71]:
hmda_all['is_hispanic'].unique()

array([0, 1])

### Filter Gender

#### Applicant Sex G

In [72]:
# applicant_sex
# Description: Sex of the applicant or borrower
# Values:
# 1 - Male
# 2 - Female
# 3 - Information not provided by applicant in mail, internet, or telephone application
# 4 - Not applicable
# 6 - Applicant selected both male and female

##### remove info not provided and NA

In [73]:
list_of_values_to_keep = [1,2,6]

hmda_all = hmda_all[hmda_all['applicant_sex'].isin(list_of_values_to_keep)]
hmda_all['applicant_sex'].unique()

array([1, 2, 6])

##### create new column with more accurate title

In [74]:
hmda_all['gender'] = hmda_all['applicant_sex']

#### count number of rows that were left after filtering for gender --> 850,102

In [75]:
# number of non-NaN values in first column
hmda_all[hmda_all.columns[0]].count()

np.int64(756291)

### Rename open-end_line_of_credit column for ease of use

In [76]:
hmda_all = hmda_all.rename(columns={'open-end_line_of_credit': 'open_end_line_of_credit'})

### Change yeses to 1s and nos to 0s

In [77]:
hmda_all['applicant_age_above_62'].unique()

array(['No', 'Yes'], dtype=object)

In [78]:
hmda_all['applicant_age_above_62'] = hmda_all['applicant_age_above_62'].replace({'Yes' : 1, 'No' : 0})

C:\Users\Cat\AppData\Local\Temp\ipykernel_15376\2091560650.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  hmda_all['applicant_age_above_62'] = hmda_all['applicant_age_above_62'].replace({'Yes' : 1, 'No' : 0})


In [79]:
hmda_all['applicant_age_above_62'].unique()

array([0, 1])

### Save Final DF as CSV

In [80]:
# save finalized dataset as csv
hmda_all.to_csv('../data/hmda_all_nf.csv', index=False)

In [90]:
import os

# Check the file size
size_bytes = os.path.getsize('../app/hmda_all_nf.csv')
size_mb = size_bytes / (1024 * 1024)
print(f"File size: {size_mb:.1f} MB")

File size: 438.8 MB


In [92]:
# Columns the app actually needs
cols_to_keep = [
    'approved_originated_or_denied',
    'lei',
    'income',
    'debt_to_income_ratio',
    'loan_to_value_ratio',
    'loan_type',
    'loan_purpose',
    'lien_status',
    'occupancy_type',
    'tract_minority_population_percent',
    'conforming_loan_limit',
    'reverse_mortgage',
    'open-end_line_of_credit',
    'business_or_commercial_purpose',
    'total_units',
    'applicant_age',
    'applicant_age_above_62',
    'aus-1', 'aus-2', 'aus-3', 'aus-4', 'aus-5',
    'denial_reason-1', 'denial_reason-2', 'denial_reason-3', 'denial_reason-4',
    # ethnicity columns
    'is_hispanic', 'ae_values_1', 'ae_values_2', 'ae_values_11', 'ae_values_12',
    'ae_values_13', 'ae_values_14',
    # race columns
    'ar_values_1', 'ar_values_2', 'ar_values_3', 'ar_values_4', 'ar_values_5',
    'ar_values_21', 'ar_values_22', 'ar_values_23', 'ar_values_24', 'ar_values_25',
    'ar_values_26', 'ar_values_27', 'ar_values_41', 'ar_values_42', 'ar_values_43',
    'ar_values_44',
]

# Only keep columns that exist
cols_to_keep = [c for c in cols_to_keep if c in hmda_all.columns]

hmda_thin = hmda_all[cols_to_keep]
hmda_thin.to_csv('../app/hmda_all_nf.csv', index=False)

print(f"Original shape: {hmda_all.shape}")
print(f"Thin shape: {hmda_thin.shape}")

Original shape: (756291, 182)
Thin shape: (756291, 48)


In [93]:
# Check the file size
size_bytes = os.path.getsize('../app/hmda_all_nf.csv')
size_mb = size_bytes / (1024 * 1024)
print(f"File size: {size_mb:.1f} MB")

File size: 107.3 MB


In [97]:
# Check what's actually in the slim file
print(hmda_thin.columns.tolist())

['approved_originated_or_denied', 'lei', 'income', 'debt_to_income_ratio', 'loan_to_value_ratio', 'loan_type', 'loan_purpose', 'lien_status', 'occupancy_type', 'tract_minority_population_percent', 'conforming_loan_limit', 'reverse_mortgage', 'business_or_commercial_purpose', 'total_units', 'applicant_age', 'applicant_age_above_62', 'aus-1', 'aus-2', 'aus-3', 'aus-4', 'aus-5', 'denial_reason-1', 'denial_reason-2', 'denial_reason-3', 'denial_reason-4', 'is_hispanic', 'ae_values_1', 'ae_values_2', 'ae_values_11', 'ae_values_12', 'ae_values_13', 'ae_values_14', 'ar_values_1', 'ar_values_2', 'ar_values_3', 'ar_values_4', 'ar_values_5', 'ar_values_21', 'ar_values_22', 'ar_values_23', 'ar_values_24', 'ar_values_25', 'ar_values_26', 'ar_values_27', 'ar_values_41', 'ar_values_42', 'ar_values_43', 'ar_values_44']


In [99]:
hmda_thin
size_bytes = os.path.getsize('../app/hmda_all_nf.csv.gz')
size_mb = size_bytes / (1024 * 1024)
print(f"Compressed size: {size_mb:.1f} MB")

Compressed size: 9.4 MB


In [96]:
# Save as gzip
hmda_thin.to_csv('../app/hmda_all_nf.csv.gz', index=False, compression='gzip')

# Check new size
import os
size_bytes = os.path.getsize('../app/hmda_all_nf.csv.gz')
size_mb = size_bytes / (1024 * 1024)
print(f"Compressed size: {size_mb:.1f} MB")

Compressed size: 9.4 MB


In [100]:
print(hmda_thin.shape)
print(hmda_thin['approved_originated_or_denied'].value_counts())

(756291, 48)
approved_originated_or_denied
1    588761
0    167530
Name: count, dtype: int64
